blog/urls.py
from blog.views import *
from django.urls import path
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog' # namespace 에러가 발생할 때 자신의 urls.py에서 지정해야 한다

urlpatterns = [
    path('admin/', admin.site.urls),
    # /blog/
    path('post/Admincommunity2', saveDB, name='saveToDB'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls',), name="blog"),
    path('', TemplateView.as_view(template_name='base.html'), name="base")
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

blog/models.py
from __future__ import unicode_literals # python 2.x 지원가능하도록 설정

blog/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
import base64
import os
import time

def remove_img(img_list, decimal, reduce_index):
    upper = 0

    for i in range(0, reduce_index):
        upper += decimal
        if upper >= 1:
            upper = round(upper % 1, 2)
            del img_list[i * 2 + 1]
        else:
            del img_list[i * 2]

    return img_list


# 클라이언트가 보내온 프레임 데이터를 서버에서 처리하는 코드 (DB 저장은 비활성화됨)
def saveDB(request):
    form = request.POST
    data = form['result_data'].split(',')

    os.makedirs('result', exist_ok=True)

    img_list = [] # 가공 전 이미지 리스트

    os.makedirs('./result/original', exist_ok=True)
    os.makedirs('./result/output', exist_ok=True)
    date = str(time.strftime('%m%d', time.localtime(time.time())))
    os.makedirs('./result/'+date, exist_ok=True)
    for i, img in enumerate(data[1::2], start=1):
        img = base64.b64decode(img)
        img_list.append(img)

        with open(os.path.join('./result/original', f'{str(i).zfill(3)}.jpg'), "wb") as f:
            f.write(img)

    # 이미지 제거
    # if len(img_list) % 2 :
    #     img_list.pop()
    #
    # center_index = int(len(img_list) / 2)
    #
    # module_dir = os.path.dirname(__file__)
    # file_path = os.path.join(module_dir, 'haarcascade_frontalface_alt.xml')
    # cascade = cv2.CascadeClassifier(file_path)
    #
    # while True:
    #     file_bytes = numpy.asarray(bytearray(img_list[center_index]), dtype=numpy.uint8)
    #     cemter_image = cv2.imdecode(file_bytes, cv2.IMREAD_GRAYSCALE)
    #
    #     center_detected = cascade.detectMultiScale(cemter_image, scaleFactor=1.1, minNeighbors=1, minSize=(30, 30))
    #
    #     if len(center_detected) > 0:
    #         first_img = img_list[0]
    #         last_img = img_list[-1]
    #         center_1_img = img_list[center_index]
    #         center_2_img = img_list[center_index+1]
    #
    #         left_img = img_list[1:center_index-1]
    #         right_img = img_list[center_index+2:-2]
    #
    #         left_img_len = len(left_img)
    #         right_img_len = len(right_img)
    #
    #         l_reduce_index = left_img_len - 62
    #         r_reduce_index = right_img_len - 62
    #
    #         l_reduce_per = 62 / l_reduce_index
    #         r_reduce_per = 62 / r_reduce_index
    #
    #         l_decimal = round(l_reduce_per % 1, 2)
    #         r_decimal = round(r_reduce_per % 1, 2)
    #
    #         left_img = remove_img(left_img, l_decimal, l_reduce_index)
    #         right_img = remove_img(right_img, r_decimal, r_reduce_index)
    #
    #         output_img = [first_img] + left_img + [center_1_img] + [center_2_img] + right_img + [last_img]
    #
    #         for k in range(len(output_img)):
    #             with open(os.path.join('./result/output', f'{str(k).zfill(3)}.jpg'), "wb") as f:
    #                 f.write(output_img[k])
    #
    #         break
    #     else:
    #         center_index += 1







    # sql_query = 'INSERT INTO image (name, image) VALUE (%s, %s)'

    # connector = pymysql.connect(user='root', password='1234', host='127.0.0.1', database='test')
    # cursor = connector.cursor()
    #
    # for j in range(1, len(data), 2):
    #     index = j//2
    #     cursor.execute(sql_query, (str(index)+'_image', data[j]))
    #
    # connector.commit()
    # connector.close()

    return render(request, 'blog/camera_ok.html')

blog/templates/blog/camera_ok.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
<h2>데이터 수신 완료</h2>
</body>
</html>

blog/templates/blog/ddd.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}homepage{% endblock %}</title>

    <meta name="description" content="main homepage">
    <meta name="author" content="Project C team">
   <!-- {#{% load staticfiles %}#} -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
</head>
<body>
<!-- {#{% block container %}#} -->
    <body style="background-color:#BEF781">
    <div class="container" >
      <div class="masthead">
        <h2 class="text-muted"><span class="label label-success"><a href="{% url 'base' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></span></h2>
          <div style="text-align:right">
 <p><span class="glyphicon glyphicon-music" aria-hidden="true"></span>*배경음악*<span class="glyphicon glyphicon-music" aria-hidden="true"></span></p>
         <audio controls="controls">
             <source src="Over_the_Horizon.mp3" type="audio/mp3"/>
             <source src="Over_the_Horizon.mp3" type="audio/ogg"/>
         </audio>
          </div>
        <nav>
          <ul class="nav nav-justified">
            <li class="active"><a href="{% url "blog:post_intro" %}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>홈페이지 소개</a></li>
            <li><a href="{% url "blog:post_community_admin" %}"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>공지사항</a></li>
              <li><a href="{% url "blog:post_community" %}"><span class="glyphicon glyphicon-search" aria-hidden="true"></span>게시판</a></li>
             <li><a href="{% url "blog:post_update" %}"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>업데이트 목록</a></li>
          </ul>
        </nav>
      </div>

      <!-- Jumbotron -->
      <div class="jumbotron">
        <h2>START NOW!!</h2>
        <p class="lead">이용하는 방법 설명문</p>
        <p><a class="btn btn-lg btn-success" href="{% url "blog:post_openSurvey" %}" role="button"><span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span>시작하기<span class="glyphicon glyphicon-hand-left" aria-hidden="true"></span></a></p>
          <div class="container text-center">
    <img src="jango.png" width="300" height="200">
  </div>
      </div>
        <hr>
        <div style=float:left;width:33%;">
            <h2>HTML & CSS <span class="glyphicon glyphicon-search" aria-hidden="true"></span></h2>
            : HTML과 CSS 웹페이지에서 정적인 요소를<br>
              표현하는 언어이다.<br>
              버튼이나 텍스트등의 요소 HTML로 표현되며<br>
              해당 요소들의 색상이나 크기등은 CSS로 표현한다
              <br>
              <br>
              <br>
              <br>
              <hr>
   <h2>자바스크립트 <span class="glyphicon glyphicon-search" aria-hidden="true"></span></h2>
              <h3>*특징*</h3>
     1.패러다임:스크립트언어,객체 지향 프로그래밍,<br>
                      함수형 프로그래밍, 사건 기반 프로그래밍<br>
              <br>
              2.발표년도: 1995년 12월 04일<br>
              <br>
              3.설계자: 브렌던 아이크<br>
              <br>
              4.개발자: 넷스케이프, 모질라재단<br>
              <br>
              5.영향을 받은 언어: 루아, 스킴, 펄, 셀프<br>
                              자바, C, 파이썬<br>
              <br>
              6.사용중인 파일 확장지: .js , .mjs
        </div>
<div style=float:left;width:33%;">
           <h2>Javascript <span class="glyphicon glyphicon-search" aria-hidden="true"></span></h2>
               : Javascript는 웹페이지에서 사용자 동작을<br>
                 정해진 로직에 따라 처리하는 언어이다.<br>
                 또한 객체기반의 스크립트 프로그래밍 언어로서,<br>
                 이 언어는 웹브라우저 내에서 주로 사용되며<br>
                 다른 응용프로그램의 내장 객체에도 접근할수 있는<br>
                 기능을 가지고 있다.
                 <br>
                 <br>
                 <hr>
            <h2>Django <span class="glyphicon glyphicon-search" aria-hidden="true"></span></h2>
            <h3>*특징*</h3>
            1.구성: 장고는 파이썬으로 코딩한 모델을<br>
                    관계형 데이터베이스로 구성 해주는<br>
                    모델(Model), HTTP요청을 처리하는<br>
                    웹 템플릿 시스템인 뷰(View)로 분리해<br>
                    URL의 라우팅을 처리하는 URL 컨트롤러<br>
                    로 구성된 MVC 디자인 패턴을 따른다.<br>
            <br>
            2.모델: 모델은 데이터에 대한 정보를 담는다.<br>
                    장고에서는 모델을 정의할때 필드의 종류를<br>
                    지정해줘야 하는데, 이것이 데이터베이스에게<br>
                    컬럼타입을 알려주고 HTML폼으로 표시될때의<br>
                    입력타입도 내포하는 역할을 한다.<br>
                    <br>
            3.뷰:   어떤 데이터가 표시되는 지를 정의한다.<br>
                    템플릿은 사용자에게 실제로 보여지는<br>
                    웹페이지나 문서를 다룬다.
</div>
        <div style=float:left;width:33%;">
            <h2>Django <span class="glyphicon glyphicon-search" aria-hidden="true"></span></h2>
               : Django는 Python 기반의 네트워크 프레임워크로<br>
                 데이터를 필요로 하거나, 서버의 자원을 필요로하는<br>
                 사용자 요청을 서버에서 처리한다.
                 또한 보안이 우수하고 유지보수가 편리하며<br>
                 무료 오픈소스 인데다가, 활발한 커뮤니티 들이 있고<br>
                 좋은 참고자료와 무료및 유료지원을 하는 옵션들이 제공된다.
            <br>
            <br>
            <hr>
   <p align="center"><h2>HTML <span class="glyphicon glyphicon-search" aria-hidden="true"></span></h2></p>
    *개발*<br>
    : 1980년, 유럽 입자 물리 연구소의 계약자였었던 물리학자 팀 버너스리가 HTML의 원형인 인콰이어를 제안했다.<br>
      1989년에 팀 버너스리는 인터넷기반 하이퍼텍스트 체계를 제안하는 메모를 작성했다.<br>
      1990년 말에 팀 버너스리는 HTML을 명시하고, 브라우저와 서버 소프트웨어를 작성했다.<br>
    <br>
    *속성*<br>
    : 대부분의 요소 속성들은 이름-값 형태이고, "="로 구분하고, 요소의 시작태그 안에서 요소의 이름 다음에 쓰인다.<br>
      값은 외따옴표 또는 쌍따옴표로 감쌀수있다.<br>
    <br>
   *데이터형식*<br>
    : HTML은 스크립트 데이터와 스타일시트 데이터, 그리고 ID, 이름, URL, 숫자 길이와 단위, 언어, 색상, 문자<br>
      등을 포함하는 속성 값의 종류를 위한 몇 가지 데이터형태를 정의 내린다.<br>
</div>

    </div> <!-- /container -->
<!-- {#{% endblock container %}#} -->

</body>
</body>
</html>

blog/templates/blog/post_Admin_detail.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width" , initial-scale="1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css"
          href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,800,700,400italic,600italic,700italic,800italic,300italic">
</head>
{% for post in posts %}
    <script type="text/javascript">
        function admin() {
            var data = prompt("관리자 패스워드 입력");
            var id = "{{ post.id }}";
            if (data == "root") {
                window.location.href = "http://127.0.0.1:8000/blog/post/AdminDoWriteBoard/" + id;
            } else {
                alert("다시 입력해주세요");
                history.go(0);
            }
        }
    </script>
    <body>
    <div class="container">
        <form action="/insertProc" method="post">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title"><b class="text-center"><h2>공지사항</h2></b></div>
                </div>
            </div>
            <hr>
            <div class="form-group">
                <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span><label><h3>제목</h3></label>
                <p>{{ post.title }}</p>
            </div>
            <hr>
            <div class="form-group">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span><label><h3>작성자</h3></label>
                <p>{{ post.user_id }}</p>
            </div>
            <hr>

            <div class="form-group">
                <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span><label><h3>작성날짜</h3></label>
                <p>{{ post.date | date:"Y-m-d" }}</p>
            </div>
            <hr>

            <div class="form-group">
                <textarea class="form-control" rows="10" style="background-color: white"
                          readonly>{{ post.content }}</textarea>
                <a href="{% url "blog:post_community_admin" %}" class="btn btn-info pull-left">뒤로가기</a>
                <input type="hidden" name="contenttext" value="" class="form-control"/>
                <a onclick="admin()" class="btn btn-info pull-right">수정하기</a>
            </div>
            <div id="id" style="display: none">{{ post.update_counter }}</div>
        </form>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    </body>
{% endfor %}

</html>

templates/backup_base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Camera Web App</title>
    <style>
        html, body {
            margin: 0;
            padding: 0;
            height: 100%;
            width: 100%;
        }
        #header {
            position: absolute;
            top: 50px;
            left: 50%;
            z-index: 999;
            color: white;
            text-align: center;
            transform: translate(-50%, -50%);
        }
        #header>p {
            font-size: 0.9em;
        }
        #camera,
        #camera--view,
        #camera--sensor,
        #camera--output {
            position: fixed;
            height: 100%;
            width: 100%;
            object-fit: cover;
        }
        #camera--view,
        #camera--sensor,
        #camera--output {
            transform: scaleX(-1);
            filter: FlipH;
        }
        #camera--trigger {
            width: 360px;
            color: white;
            background-color: gray;
            font-size: 35px;
            border-radius: 30px;
            border: none;
            padding: 35px 20px;
            text-align: center;
            box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0, 0.2);
            position: fixed;
            bottom: 60px;
            left: calc(50% - 270px);
        }
        .taken {
            height: 140px !important;
            width: 220px !important;
            border: solid 2px rgb(121, 200, 253);
        }

        #camera--capture {
            width: 140px;
            color: white;
            background-color: black;
            font-size: 35px;
            border-radius: 30px;
            border: none;
            padding: 35px 20px;
            text-align: center;
            box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0, 0.2);
            position: fixed;
            bottom: 60px;
            left: calc(80% - 90px);
        }
        .taken {
            height: 140px !important;
            width: 220px !important;
            border: solid 2px rgb(121, 200, 253);
        }

    </style>
</head>
<body>
    <div id="header">
        <h3>Simple Web Camera</h3>
        <p>버튼을 클릭 하세요.</p>
        <canvas id="canvas"></canvas>
<div style="display:none;">
  <img id="source"
       src="https://mdn.mozillademos.org/files/5397/rhino.jpg"
       width="300" height="227">
</div>
    </div>

    <!-- main 태그는 문서의 주요 내용을 담는 태그이다. 한 문서에 한개 존재 해야 한다.
    또한 article, aside, header, nav, footer등 요소의 하위에 사용해서는 안된다.-->
    <main id="camera">
        <canvas id="camera--sensor"></canvas>
        <!-- 기기의 카메라에 접근하여 영상을 페이지에 재생한다. -->
        <video id="camera--view" autoplay playsinline></video>
        <img src="//:1" alt="" id="camera--output">




        <button id="camera--trigger">사진촬영</button>

        <form action="{% url "blog:saveToDB" %}" method='POST'>{% csrf_token %}
            <button id="camera--capture">전송</button>
            <input type="hidden" name="result_data" value="" id="js_data_input">
        </form>


    </main>

    <script>
        var front = true;
        var imgList = [];
        // https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/facingMode
        let constraints = { video: { facingMode: (front? "user" : "environment") } };
        //let constraints = { video: { facingMode: "user" }, audio: false };
        const cameraView = document.querySelector("#camera--view");
        const cameraOutput = document.querySelector("#camera--output");
        const cameraSensor = document.querySelector("#camera--sensor");
        const cameraTrigger = document.querySelector("#camera--trigger");

        const image = document.getElementById('source');

        window.onload = function cameraStart() {
            navigator.mediaDevices.getUserMedia(constraints)
                .then(function (stream) {
                    track = stream.getTracks()[0];
                    cameraView.srcObject = stream;


                })
                .catch(function (error) {
                    console.error("카메라에 문제가 있습니다.", error);
                })
        }


        //촬영 버튼 클릭 리스너
        cameraTrigger.addEventListener("click", function () {

            cameraSensor.width = cameraView.videoWidth; //640으로 정해져서 나오네?
            cameraSensor.height = cameraView.videoHeight;
            cameraSensor.getContext("2d").drawImage(cameraView, 0, 0);
            cameraOutput.src = cameraSensor.toDataURL("image/webp");
            camera_src = cameraSensor.toDataURL("image/png");
            cameraOutput.classList.add("taken");
            console.log(cameraView.srcObject);
            imgList.push(camera_src);
            document.getElementById("js_data_input").value = imgList;



        });

        // 페이지가 로드되면 함수 실행
        window.addEventListener("load", cameraStart, false);


    </script>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {
            text-align: center;
            margin: 0;
            padding: 0;
        }
        video {
            background-color: black;
            z-index: -1;
            width: 100%;
            height: auto;
        }
        #guideline {
            background-color: rgba(0, 0, 0, 0);
            position: absolute;
            top: 0;
            left: 0;
            z-index: 1;
            width: 100%;
            height: auto;
        }
        #canvas {
            background-color: rgba(127, 127, 127, 0.5);
            position: absolute;
            top: 0;
            left: 0;
            z-index: 2;
            width: 100%;
            height: auto;
        }
        button, div{
            font-size: 5rem;
        }
        button {
            margin-right: 2rem;
        }
        form {
            display: inline;
        }
    </style>
    <title>Hologram Photo</title>
    <link rel="icon" href="data:;base64,iVBORw0KGgo=">
</head>
<script src="https://docs.opencv.org/3.4/opencv.js"></script>
<!-- 구성요소 생성 -->
<body onload="onLoad()">
    <video id="video" autoplay muted></video>
    <canvas id="guideline"></canvas>
    <canvas id="canvas"></canvas>
    <div id="timer">8초</div>
    <button id="switch_camera" onclick="switchCamera()">카메라 전환</button>
    <button id="record" onclick="record()">녹화</button>
    <form action="{% url "blog:saveToDB" %}" method="POST">{% csrf_token %}
        <button id="send" onclick="sendData()" disabled>전송</button>
        <input type="hidden" name="result_data" value="" id="js_data_input">
    </form>
    <div>
        <progress id="progress" value="20" max="100"></progress>
    </div>
</body>
<script>
    let front_camera = false    // 전면 카메라 사용 유무
    let width = 640     // 해상도 (너비)
    let height = 480    // 해상도 (높이)
    let camera_resolution = [width, height]     // 해상도
    const fps = 30      //FPS
    const capture_time = 8  // 캡쳐 시간
    const video = document.getElementById('video')
    const canvas = document.getElementById('canvas')
    const guideline = document.getElementById('guideline')
    const progressBar = document.getElementById('progress')
    let src, cap, start_date
    let frames = []     // 캡쳐한 프레임들을 임시로 저장하는 배열

    // 페이지를 로드하면 실행 (구성요소들 초기화)
    function onLoad() {
        if (navigator.platform.indexOf('arm') !== -1 || navigator.platform.indexOf('aarch') !== -1) {
            [width, height] = [height, width]
        }
        video.width = width
        video.height = height
        canvas.width = width
        canvas.height = height
        guideline.width = width
        guideline.height = height
        canvas.style.visibility = 'hidden'
        stream()
        draw_guideline()
    }

    // 웹에서 카메라 사용을 위한 스트림 생성
    function stream() {
        navigator.getUserMedia(
            {video: {facingMode: (front_camera ? "user" : "environment"),
                    width: camera_resolution[0],
                    height: camera_resolution[1]}, audio: false},
            function (stream){video.srcObject = stream; video.play()},
            function (err){alert(err)}
        )
    }

    // 카메라 프리뷰에 십자 안내선 생성
    function draw_guideline() {
        let context = guideline.getContext('2d')
        context.strokeStyle = 'white'
        context.beginPath()
        context.moveTo(0, guideline.height / 2)
        context.lineTo(guideline.width, guideline.height / 2)
        context.moveTo(guideline.width / 2, 0)
        context.lineTo(guideline.width / 2, guideline.height)
        context.stroke()
    }

    // 전/후면 카메라 전환
    function switchCamera() {
        front_camera = !front_camera
        video.srcObject.getTracks().forEach(track => {track.stop()})
        stream()
    }

    // 녹화 시작 버튼을 누르면 3초 대기 후 실제 녹화 시작
    async function standby(time=3, print_offset=80) {
        let context = canvas.getContext('2d')
        context.font = '20rem Arial'
        context.fillStyle = 'white'

        for (; time >= 1; time--) {
            context.clearRect(0, 0, canvas.width, canvas.height)
            context.fillText(String(time), canvas.width / 2 - print_offset, canvas.height / 2 + print_offset)
            await sleep(1000)
        }
    }

    // 녹화 버튼을 클릭하면 실행되는 메소드
    async function record() {
        document.getElementById('switch_camera').disabled = true
        document.getElementById('record').disabled = true
        document.getElementById('send').disabled = false
        canvas.style.visibility = 'visible'
        await standby()
        video.style.visibility = 'hidden'

        src = new cv.Mat(height, width, cv.CV_8UC4)
        cap = new cv.VideoCapture('video')
        start_date = Date.now()
        let audio = new Audio('/static/beep.mp3')

        recordVideo()
        for (let i = 0; i <= capture_time; i++) {
            audio.play()
            await sleep(1000)
        }
    }

    // 실제 녹화
    function recordVideo() {
        let begin = Date.now()
        cap.read(src)
        cv.imshow('canvas', src)
        frames.push(canvas.toDataURL('image/jpeg'))

        let passed_time = (Date.now() - start_date) / 1000
        document.getElementById('timer').textContent = String(Math.ceil(capture_time - passed_time)) + '초'
        if (passed_time >= capture_time) {
            src.delete()
            return
        }
        setTimeout(recordVideo, 1000 / fps - (Date.now() - begin))
    }

    // 서버로 프레임 데이터 전송
    function sendData() {
        document.getElementById('send').style.visibility = 'hidden'
        document.getElementById('js_data_input').value = frames
        progressBar.value = 100;
    }

    // 지정된 시간만큼 코드 실행 대기
    function sleep(ms) {
        return new Promise((r) => setTimeout(r, ms));
    }
</script>
</html>

templates/record_base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="'viewport" content="width=device-width, inital-scale=1.0">
    <title>Video Capture</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }
        html, body {
            height: 100%;
        }
        .wrapper {
            height: 100%;
            overflow: hidden;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }
        .video-container {
            display: flex;
            width: 550px;
            padding: 1rem;
            justify-content: space-around;
        }
        .video-item > h2 {
            text-align: center;
        }
        .video-item > video {
            border: 1px solid red;
            width: 550px;
            height: 550px;
        }
        button, a {
            border: none;
            font-size: 14px;
            background: #ccc;
            padding: 0.5rem 1rem;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="button-container">
            <button class="record-button">녹화</button>
            <button class="stop-button">중지</button>
            <button class="play-button">녹화보기</button>
            <a class="download-button" target="_blank">다운로드</a>
            <form action="{% url "blog:saveToDB" %}" method='POST'>{% csrf_token %}
                <button>전송</button>
                <input type="hidden" name="result_data" value="" id="js_data_input">
            </form>
        </div>
        <div class="video-container">
            <div class="video-item">
                <h2>미리보기</h2>
                <video autoplay muted id="preview"></video>
            </div>
            <div class="video-item">
                <h2>미리보기</h2>
                <video id="recording"></video>
            </div>
        </div>
    </div>
    <script>
        // DOM
        const recordButton = document.querySelector(".record-button")
        const stopButton = document.querySelector(".stop-button")
        const playButton = document.querySelector(".play-button")
        const downloadButton = document.querySelector(".download-button")

        // 비디오 플레이어
        const previewPlayer = document.querySelector("#preview")
        const recordingPlayer = document.querySelector("#recording")

        let recorder;
        var recordedChunks = []; // 데이터 담는 용도
        var wavfromblob;

        function videoStart(){
            navigator.mediaDevices.getUserMedia({ video: true, audio: true}).then(
                stream => {
                    previewPlayer.srcObject = stream;
                    startRecording(previewPlayer.captureStream())
                }
            )
        }

        function startRecording(stream){
            recordedChunks = [];
            recorder = new MediaRecorder(stream);
            recorder.ondataavailable = (e) => { recordedChunks.push(e.data)}; // 이벤트에 데이터를 담아서 . 녹화된 내용이 여기에 담김
            recorder.start();
         }

        function stopRecording(){
            previewPlayer.srcObject.getTracks().forEach(track => track.stop()) //배열이기 때문에 이렇게 사용 16:40초 내용 언급
            recorder.stop();
        }

        function playRecording(){
            const recordedBlob = new Blob(recordedChunks, {type: "video/mp4"}); // 파라미터 : (비디오 데이터가 담긴 배열, 확장자)
            recordingPlayer.src = URL.createObjectURL(recordedBlob);
            console.log(recordingPlayer.src)
            document.getElementById("js_data_input").value = recordingPlayer.src;
            recordingPlayer.play();
            downloadButton.href = recordingPlayer.src;
            downloadButton.download = 'recording.mp4';
        }

        // 이벤트 처리
        recordButton.addEventListener("click", videoStart);
        stopButton.addEventListener("click", stopRecording);
        playButton.addEventListener("click", playRecording);
    </script>
</body>
</html>